import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

import TestBarChart from "~/components/TestBarChart";

const CountryInflationCard = () => {
  return (
    <div className="mb-[90px] w-full px-5 sm:w-full md:w-1/2 lg:w-1/3 xl:w-1/3">
      <div className="h-[300px] xl:w-[400px]">
        <TestBarChart />
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>US vs Asia Inflation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#cccccc] to-[#666668]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 bg-blue-900">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            US <span className="text-[hsl(280,100%,70%)]">VS</span> Asia
            Inflation
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>

          <div className="flex flex-wrap">
            <CountryInflationCard />
            <CountryInflationCard />
            <CountryInflationCard />
          </div>

          <p className="mt-20 text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
